server:
  port: 8011
  
spring:
  application:
    name: microservice-consumer-movie-feign-customzing-without-hystrix
    
eureka:
  client:
    service-url:
      defaultZone: http://micheal:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true 

logging:
  level:
    com.spring.cloud.feign.UserFeignClient: DEBUG
   
#设置Hystrix的超时时间为5秒
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000