server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://micheal:123456@localhost:8761/eureka/ #http://peer1:8762/eureka/,http://peer2:8763/eureka/
#    registry-refresh-single-vip-address: ${spring.application.name}
  instance:
    prefer-ip-address: true
    
turbine:
  aggregator:
    clusterConfig: default
  appConfig: microservice-consumer-movie-ribbon-with-hystrix,microservice-consumer-movie-feign-with-hystrix
  clusterNameExpression: "'default'" #或者 new String("default")一样
  
#这个配置时所有的集群监控的都配置
#    clusterConfig: MICROSERVICE-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX,MICROSERVICE-CONSUMER-MOVIE-FEIGN-WITH-HYSTRIX
#  appConfig: microservice-consumer-movie-ribbon-with-hystrix,microservice-consumer-movie-feign-with-hystrix
