server:
  port: 8010
  
spring:
  application:
    name: microservice.consumer.movie.ribbon
    
eureka:
  client:
    service-url:
      defaultZone: http://micheal:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true 

#取消Ribbon使用Eureka
ribbon:
  eureka:
   enabled: false
   
#配置Ribbon能访问 的微服务节点，多个节点用逗号隔开
microservice-provider-user:
  ribbon:
    listOfServers: localhost:7900
    