server:
  port: 8010
  
spring:
  application:
    name: microservice-consumer-movie-ribbon-properties-custom
    
eureka:
  client:
    service-url:
      defaultZone: http://micheal:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true 

#配置文件中配置Ribbon
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule    #这里配置随机规则